# Generated by Django 5.1.1 on 2025-11-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
    ]
