# Generated by Django 5.1.1 on 2025-12-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0002_auto_20251126_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment_app.assessment'),
        ),
    ]
