# Generated by Django 4.2.28 on 2026-02-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0003_response_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment_app.assessment'),
        ),
    ]
