# Generated by Django 4.2.28 on 2026-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0004_alter_response_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('questions_data', models.JSONField(default=list)),
                ('answers_data', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
