# Generated by Django 4.2.28 on 2026-02-20 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0005_careerassessment_remove_assessment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('results_app', '0005_alter_result_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
