# Generated by Django 4.2.28 on 2026-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0006_delete_assessment_delete_question_delete_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerassessment',
            name='insights',
            field=models.JSONField(default=dict),
        ),
    ]
