# Generated by Django 5.1.1 on 2025-12-23 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('category', models.CharField(blank=True, choices=[('personality', 'Personality'), ('interest', 'Interest'), ('values', 'Values')], max_length=20, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'psychometric_questions',
            },
        ),
        migrations.CreateModel(
            name='PsychometricSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('standalone', 'Standalone'), ('full', 'Full Assessment')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psychometric_sessions',
            },
        ),
        migrations.CreateModel(
            name='PsychometricResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_score', models.IntegerField()),
                ('interest_score', models.IntegerField()),
                ('values_score', models.IntegerField()),
                ('personality_percentile', models.IntegerField()),
                ('interest_percentile', models.IntegerField()),
                ('values_percentile', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='psychometric_app.psychometricsession')),
            ],
            options={
                'db_table': 'psychometric_results',
            },
        ),
        migrations.CreateModel(
            name='PsychometricResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychometric_app.psychometricquestion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='psychometric_app.psychometricsession')),
            ],
            options={
                'db_table': 'psychometric_responses',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
