# Generated by Django 5.2.8 on 2026-01-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('verbal', 'Verbal Reasoning'), ('personality', 'Personality Tests'), ('sjt', 'Situational Judgment Tests')], unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Short description for the hub card')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('format', 'Format & Structure'), ('types', 'Question Types'), ('rules', 'Rules'), ('tips', 'Preparation Tips'), ('intro', 'Introduction/Concept'), ('scoring', 'Scoring'), ('examples', 'Examples'), ('categories', 'Categories'), ('differences', 'Differences')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='HTML allowed')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='learning.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
