# Generated by Django 5.1.1 on 2026-02-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_screeningdomain_screeningquestion_screeningsession_and_more'),
    ]

    operations = [
    ]
