# Generated by Django 4.2.28 on 2026-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_seed_screening_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
