# Generated by Django 4.2.28 on 2026-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('15-24', '15-24'), ('25-34', '25-34'), ('35-45', '35-45')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20, null=True),
        ),
    ]
